### ISSUE TITLE
Line Numbers Overlapping

### ISSUE THREAD

**Issue by JSn1nj4** [Murriouz/dark-bint-syntax#1]
Every 7th line number ends up underneath every 6th line number. Playing around right now with the theme's .less files to see if I can fix the issue.

To be sure it wasn't the Syntax theme, I did try switching the UI theme. The issue was still there though. Also, I listed the current version of Atom I'm using, but I only just updated to that version after installing this theme. Previous version was 1.2.1.

Atom version: 1.2.2
Theme version: 0.5.0
OS: Windows 10

Also, after looking at your repo, I see changes you already made to fix this (b02b563). I can confirm they work.
![atom-bint-gutter-problem](https://cloud.githubusercontent.com/assets/5084820/11279276/8775c546-8ebd-11e5-8529-bda0e1df5542.png)

**Comment by thethreeonee** [comment]
Published new version.

**Comment by JSn1nj4** [comment]
Sorry I never replied to this. Issue is fixed. Thanks.
