### ISSUE TITLE
Line number alignment in gutter

### ISSUE THREAD

**Issue by JSn1nj4** [Murriouz/dark-bint-syntax#2]
The font used in the line numbers (PT Mono) throws off alignment. When I disable it in the dev tools, the alignment is fixed.

At first I thought the spaces themselves weren't monospace (as if they were overlooked by the font artist). But now I'm not sure why they're behaving this way...

![atom-bint-gutter-problem-number-alignment-bad](https://cloud.githubusercontent.com/assets/5084820/11285400/50680030-8edd-11e5-9bed-926fe089410b.png)

![atom-bint-gutter-problem-number-alignment](https://cloud.githubusercontent.com/assets/5084820/11285297/bf5f4da0-8edc-11e5-915d-5ad41612b74b.png)

**Comment by JSn1nj4** [comment]
Just a followup: I don't think I have that font installed... That said, you may still want to remove "PT Mono" from your styles, in case anyone else doesn't have it.

On mine, I tried changing it to Source Code Pro, and the alignment was fine.

**Comment by thethreeonee** [comment]
Fixed in new version.

**Comment by JSn1nj4** [comment]
Thanks.
