### ISSUE TITLE
An opinion

### ISSUE THREAD

**Issue by withflx** [Murriouz/dark-bint-syntax#3]
Your syntax theme, gosh! Been looking all over for a theme to fall in love with, and then I found yours!

When typing in my .css-file
I think that the ".selected" and ":hover" should have some other color than the standard.
For example:
nav a.selected, nav a:hover {
    color: #32673f;
}

Hope you can consider this, so I can continue to brag about the color scheme. :happy

**Comment by thethreeonee** [comment]
It sounds good. I've updated the syntax.
